theme: jekyll-theme-slate
title: basicMLpy
description: Python package for Machine Learning
markdown: kramdown
highlighter: rouge
pages:
- Home: index.md
- Install: install.md
- User Guide: user_guide.md
- Coming up: coming_up_next.md
- About: about.md
