theme: jekyll-theme-slate
title: basicMLpy
description: Python package for Machine Learning
markdown: kramdown
highlighter: rouge
navigation: 
 - title: Home
   url: /index.md
 - title: Install
   url: /install
